### ISSUE TITLE
Release 8.0.2 failed to publish documentation

### ISSUE THREAD

**Issue by matrei** [grails/gorm-docs#18]
Attaching saved workflow logs if they are purged:
[logs_45.zip](https://github.com/grails/gorm-docs/files/13389147/logs_45.zip)

**Comment by guillermocalvo** [comment]
@matrei Looks like a network glitch to me 🤔 

```
Could not resolve all files for configuration ':rx:documentation'.
> Could not find org.grails:grails-datastore-core:8.0.2.
  Searched in the following locations:
    - https://repo.grails.org/grails/core/org/grails/grails-datastore-core/8.0.2/grails-datastore-core-8.0.2.pom
...
```

But I can see that artifact right there: https://repo.grails.org/ui/native/core/org/grails/grails-datastore-core/8.0.2/

Maybe we should just execute it again? WDYT @puneetbehl?

**Comment by puneetbehl** [comment]
This is resolved now
