### ISSUE TITLE
Version 8.1.0 MongoDB - All sections contain the error "Unresolved directive in index.adoc - include::${reference}"

### ISSUE THREAD

**Issue by MitchyGoodness** [grails/gorm-docs#19]
Link: [MongoDB manual](https://gorm.grails.org/8.1.0/mongodb/manual/index.html)
All sections except the introduction contain an unresolved error.

> Compatibility with GORM for Hibernate
> Unresolved directive in index.adoc - include::introduction/compatibility.adoc[]
> 
> Release Notes
> Unresolved directive in index.adoc - include::introduction/releaseNotes.adoc[]
> 
> Upgrade Notes
> Unresolved directive in index.adoc - include::introduction/upgradeNotes.adoc[]

**Comment by MitchyGoodness** [comment]
Thanks for taking care of that @puneetbehl! Do you know when the changes will be deployed?

**Comment by puneetbehl** [comment]
I will try to get it out by this week.

**Comment by MitchyGoodness** [comment]
For anyone needing a quick alternative, here's the [MongoDB 7.0.0 manual](https://grails.github.io/legacy-gorm-doc/7.0.0/mongodb/manual/index.html)
