### ISSUE TITLE
gorm.grails.org should mention the latest heading to GORM 7

### ISSUE THREAD

**Issue by puneetbehl** [grails/gorm-docs#3]
See http://gorm.grails.org

**Comment by sdelamo** [comment]
what is the issue exactly?

**Comment by puneetbehl** [comment]
If you go to gorm.grails.org, then there is a heading which mentioned "GORM 6 - A powerful Groovy-based data access toolkit for the JVM". I think it should be GORM 7.

See the following screenshot:

![Screenshot 2020-04-07 at 12 22 05 AM](https://user-images.githubusercontent.com/2108607/78594534-1c98e180-7866-11ea-9543-9117f0b49742.png)
